name: Render and deploy Quarto files
on: 
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
    - uses: actions/checkout@v2

    - name: Install libcurl
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcurl4-openssl-dev
          
    - name: "Install R Packages: Restore packages"
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()
        
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
        
    - name: Render Quarto Document Manually
      run: |
        Rscript -e "install.packages('quarto')"
        Rscript -e "library(quarto); render_document('index.qmd')"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: document_output