on:
  push:
    branches: main

name: update deck

jobs:
  generate-data:
    name: update deck
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:

      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          # don't reinstall R
          install-r: false
          # use RStudio's CRAN mirror with precompiled binaries
          use-public-rspm: true

      - name: Install libcurl
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        shell: Rscript {0}
        run: |
          quarto::quarto_render("index.qmd")
          
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

